
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mariadb://blogdb.cqg41lvwng6q.ap-northeast-2.rds.amazonaws.com/ugoblogdb
    username: ugo
    password: asdasd12!
    driver-class-name: org.mariadb.jdbc.Driver
server:
  port: 8080

mail:
  admin-email: ugosdevblog@gmail.com
  admin-pwd : tggxivvagqbqjzky
  subject: UGO'S Dev Blog에 요청하신 인증번호입니다
  from-mail: ugosdevblog@gmail.com
  from-name: Ugo's Dev blog