spring:
  banner:
    image:
      location: classpath:static/banner.png
      width: 90
      height: 15
      bit-depth: 8
      margin: 0
  config:
    import:
      - classpath:database.yml
      - classpath:mail.yml
server:
  port: 8080
app:
  sdk-host: https://ugo-blog-image-bucket.s3.ap-northeast-2.amazonaws.com/
  sdk-access-key: AKIAVHMSY34H33KIV25X
  sdk-secret-key: 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
  sdk-bucket-name: ugo-blog-image-bucket

