
server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: true
  datasource:
    url: jdbc:mariadb://blogdb.cqg41lvwng6q.ap-northeast-2.rds.amazonaws.com/ugoblogdb
    username: ugo
    password: asdasd12!
    driver-class-name: org.mariadb.jdbc.Driver