spring:
  banner:
    image:
      location: classpath:static/banner.png
      width: 90
      height: 15
      bit-depth: 8
      margin: 0
  config:
    import:
      - classpath:database.yml
      - classpath:mail.yml
      - classpath:aws.yml
server:
  port: 8080
db:
  credential-path: /home/ubuntu/DBCredential.yml



