spring:
  banner:
    image:
      location: classpath:static/banner.png
      width: 90
      height: 15
      bit-depth: 8
      margin: 0
  config:
    import:
      - classpath:database.yml
      - classpath:mail.yml
server:
  port: 8080
db:
  credential-path: /Users/ugo/DBCredential.yml
app:
  credential-path: /Users/ugo/credential.yml
  sdk-host: https://ugo-blog-image-bucket.s3.ap-northeast-2.amazonaws.com/
  sdk-bucket-name: ugo-blog-image-bucket


