spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/ugosdevblog
    username: sa
    password:
    driver-class-name: org.h2.Driver
server:
  port: 8080

mail:
  admin-email: ugosdevblog@gmail.com
  admin-pwd : tggxivvagqbqjzky
  subject: UGO'S Dev Blog에 요청하신 인증번호입니다
  from-mail: ugosdevblog@gmail.com
  from-name: Ugo's Dev blog