spring:
  banner:
    image:
      location: classpath:static/banner.png
      width: 90
      height: 15
      bit-depth: 8
      margin: 0
  config:
    import:
      - classpath:database.yml
      - classpath:mail.yml

app:
  db:
#    credential-path: /home/ubuntu/DBCredential.yml
    credential-path: /Users/ugo/DBCredential.yml
  aws:
#    credential-path: /home/ubuntu/credential.yml
    credential-path: /Users/ugo/credential.yml
    sdk-host: https://ugo-blog-image-bucket.s3.ap-northeast-2.amazonaws.com/
    sdk-bucket-name: ugo-blog-image-bucket


---
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod1

---
server:
  port: 8081

spring:
  config:
    activate:
      on-profile: prod2
