
spring:
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
  datasource:
    url: jdbc:mariadb://blogdb.cqg41lvwng6q.ap-northeast-2.rds.amazonaws.com/ugoblogdb
    username: ugo
    password: asdasd12!
    driver-class-name: org.mariadb.jdbc.Driver
server:
  port: 9000

#---
#
#spring:
#  profiles:
#    active: dev
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        default_batch_fetch_size: 100
#    open-in-view: true
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/ugosdevblog
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#server:
#  port: 8080

