server:
  port: 9050

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  security:
    user:
      name: ugo
      password: asdasd1
      roles: USER

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/ugosdevblog
    username: sa
