
app:
  credential-path: /home/ubuntu/credential.yml
  sdk-host: https://ugo-blog-image-bucket.s3.ap-northeast-2.amazonaws.com/
  sdk-bucket-name: ugo-blog-image-bucket
spring:
  config:
    activate:
      on-profile: prod
---

app:
  credential-path: /Users/ugo/credential.yml
  sdk-host: https://ugo-blog-image-bucket.s3.ap-northeast-2.amazonaws.com/
  sdk-bucket-name: ugo-blog-image-bucket
spring:
  config:
    activate:
      on-profile: dev

