
app:
  db-credential-path: /Users/ugo/DBCredential.yml
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: true
  config:
    activate:
      on-profile: dev
---
app:
  db-credential-path: /home/ubuntu/DBCredential.yml
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
  config:
    activate:
      on-profile: prod
